descriptions = [
    {
        "name": "run_mriqc",
        "module": "tool_lib.quality_control_lib",
        "description": "Call MRIQC tool to calculate image quality metrics (IQMs) on all subjects and generate corresponding quality reports for quality control before any preprocessing.",
        "detailed_schema": """
            **Parameters:**
            - bids_dir (str): Absolute path to the BIDS input dataset.
            - output_dir (str): Absolute path to the output directory. 
            - modality (list[str]): Specific modality to measure, valid options are 'T1w' and 'bold'.

            **Outputs:**
            - Artifacts generated by MRIQC under `output_dir`:
            - For each processed subject `sub-<label>`:
                - Image quality metrics (IQMs) JSON files, e.g.:
                - `sub-<label>/ses-<label>/anat/sub-<label>_T1w.json`
                - `sub-<label>/ses-<label>/func/sub-<label>_*_bold.json` (if BOLD exists)
                - Per-image HTML report, e.g.:
                - `sub-<label>_ses-<label>_T1w.html`
                - `sub-<label>_ses-<label>_bold.html`

            This python tool itself has no return value, only generates MRIQC derivatives in the corresponding output_dir.
        """
    },

    {
        "name": "get_mriqc_group_level_tsv_and_outliers",
        "module": "tool_lib.quality_control_lib",
        "description": "Get the group-level TSV (`group_T1w.tsv` / `group_bold.tsv` in `output_dir`) and detected outliers of MRIQC IQMs from group-level MRIQC results.",
        "detailed_schema": """
            **Parameters:**
            - modality (str): 'T1w' or 'bold'.
            - metric_keys (list[str] | None): IQM metrics to evaluate; if None, use all numeric columns.
                - For T1w: valid metric keys include: ['cjv',	'cnr',	'efc',	'fber',	'fwhm_avg',	'fwhm_x',	'fwhm_y',	'fwhm_z',	'icvs_csf',	'icvs_gm',	'icvs_wm',	'inu_med',	'inu_range',	'qi_1',	'qi_2',	'rpve_csf',	'rpve_gm',	'rpve_wm',	'size_x',	'size_y',	'size_z',	'snr_csf',	'snr_gm',	'snr_total',	'snr_wm',	'snrd_csf',	'snrd_gm',	'snrd_total',	'snrd_wm',	'spacing_x',	'spacing_y',	'spacing_z',	'summary_bg_k',	'summary_bg_mad',	'summary_bg_mean',	'summary_bg_median',	'summary_bg_n',	'summary_bg_p05',	'summary_bg_p95',	'summary_bg_stdv',	'summary_csf_k',	'summary_csf_mad',	'summary_csf_mean',	'summary_csf_median',	'summary_csf_n',	'summary_csf_p05',	'summary_csf_p95',	'summary_csf_stdv',	'summary_gm_k',	'summary_gm_mad',	'summary_gm_mean',	'summary_gm_median',	'summary_gm_n',	'summary_gm_p05',	'summary_gm_p95',	'summary_gm_stdv',	'summary_wm_k',	'summary_wm_mad',	'summary_wm_mean',	'summary_wm_median',	'summary_wm_n',	'summary_wm_p05',	'summary_wm_p95',	'summary_wm_stdv',	'tpm_overlap_csf',	'tpm_overlap_gm',	'tpm_overlap_wm',	'wm2max'].
                - For bold: valid metric keys include: ['aor',	'aqi',	'dummy_trs',	'dvars_nstd',	'dvars_std',	'dvars_vstd',	'efc',	'fber',	'fd_mean',	'fd_num',	'fd_perc',	'fwhm_avg',	'fwhm_x',	'fwhm_y',	'fwhm_z',	'gcor',	'gsr_x',	'gsr_y',	'size_t',	'size_x',	'size_y',	'size_z',	'snr',	'spacing_tr',	'spacing_x',	'spacing_y',	'spacing_z',	'summary_bg_k',	'summary_bg_mad',	'summary_bg_mean',	'summary_bg_median',	'summary_bg_n',	'summary_bg_p05',	'summary_bg_p95',	'summary_bg_stdv',	'summary_fg_k',	'summary_fg_mad',	'summary_fg_mean',	'summary_fg_median',	'summary_fg_n',	'summary_fg_p05',	'summary_fg_p95',	'summary_fg_stdv',	'tsnr'].
            - output_dir (str): MRIQC output root directory containing the group-level TSV, same as the output_dir of `run_mriqc` tool.
            - temp_work_dir (str): Absolute path to the temporary work directory.

            **Outputs:**
            - group-level TSV: `group_T1w.tsv` / `group_bold.tsv` in `output_dir`
            - dict: A python dictionary with the following keys when successful:
                - modality (str): Either 'T1w' or 'bold' (normalized from input).
                - metrics (list[str]): The numeric IQM metric names that were evaluated.
                - stats (dict[str, dict]): Per-metric summary statistics and IQR bounds.
                    For each metric, includes:
                        - count (int): Number of non-NaN samples used.
                        - q1 (float): 25th percentile.
                        - q3 (float): 75th percentile.
                        - iqr (float): Interquartile range (q3 - q1).
                        - lower_bound (float): Outlier lower bound (q1 - 1.5 * iqr).
                        - upper_bound (float): Outlier upper bound (q3 + 1.5 * iqr).
                - outliers (list[dict]): A list of detected outlier records. Each record contains:
                    - bids_name (str): Scan identifier from the TSV 'bids_name' column.
                    - metric (str): Metric name where the outlier was detected.
                    - value (float): Metric value (rounded to 4 decimals).
                    - direction (str): 'Too low' or 'Too high'.
        """
    },

    {
        "name": "read_mriqc_metric",
        "module": "tool_lib.quality_control_lib",
        "description": "Read MRIQC IQM metrics for a specified subject and modality, optionally filtering by metric keys.",
        "detailed_schema": """
            **Parameters:**
            - subject_label (str): Subject ID with or without the 'sub-' prefix (e.g., '0027003' or 'sub-0027003').
            - modality (str): Target modality, one of 'T1w' or 'bold'.
            - metric_keys (list[str] | None): Specific IQM keys to return; if None, return all available IQMs.
                - For T1w: valid metric keys include: ['cjv',	'cnr',	'efc',	'fber',	'fwhm_avg',	'fwhm_x',	'fwhm_y',	'fwhm_z',	'icvs_csf',	'icvs_gm',	'icvs_wm',	'inu_med',	'inu_range',	'qi_1',	'qi_2',	'rpve_csf',	'rpve_gm',	'rpve_wm',	'size_x',	'size_y',	'size_z',	'snr_csf',	'snr_gm',	'snr_total',	'snr_wm',	'snrd_csf',	'snrd_gm',	'snrd_total',	'snrd_wm',	'spacing_x',	'spacing_y',	'spacing_z',	'summary_bg_k',	'summary_bg_mad',	'summary_bg_mean',	'summary_bg_median',	'summary_bg_n',	'summary_bg_p05',	'summary_bg_p95',	'summary_bg_stdv',	'summary_csf_k',	'summary_csf_mad',	'summary_csf_mean',	'summary_csf_median',	'summary_csf_n',	'summary_csf_p05',	'summary_csf_p95',	'summary_csf_stdv',	'summary_gm_k',	'summary_gm_mad',	'summary_gm_mean',	'summary_gm_median',	'summary_gm_n',	'summary_gm_p05',	'summary_gm_p95',	'summary_gm_stdv',	'summary_wm_k',	'summary_wm_mad',	'summary_wm_mean',	'summary_wm_median',	'summary_wm_n',	'summary_wm_p05',	'summary_wm_p95',	'summary_wm_stdv',	'tpm_overlap_csf',	'tpm_overlap_gm',	'tpm_overlap_wm',	'wm2max'].
                - For bold: valid metric keys include: ['aor',	'aqi',	'dummy_trs',	'dvars_nstd',	'dvars_std',	'dvars_vstd',	'efc',	'fber',	'fd_mean',	'fd_num',	'fd_perc',	'fwhm_avg',	'fwhm_x',	'fwhm_y',	'fwhm_z',	'gcor',	'gsr_x',	'gsr_y',	'size_t',	'size_x',	'size_y',	'size_z',	'snr',	'spacing_tr',	'spacing_x',	'spacing_y',	'spacing_z',	'summary_bg_k',	'summary_bg_mad',	'summary_bg_mean',	'summary_bg_median',	'summary_bg_n',	'summary_bg_p05',	'summary_bg_p95',	'summary_bg_stdv',	'summary_fg_k',	'summary_fg_mad',	'summary_fg_mean',	'summary_fg_median',	'summary_fg_n',	'summary_fg_p05',	'summary_fg_p95',	'summary_fg_stdv',	'tsnr'].
            - output_dir (str): Absolute path to the MRIQC output root directory.

            **Outputs:**
            - dict: On success, returns a dict with:
                - subject (str): normalized subject label with 'sub-' prefix
                - modality (str): 'T1w' or 'bold'
                - metrics (dict): IQM key-value pairs (all IQMs if metric_keys is None; otherwise only requested keys, missing keys -> None)
            - str: On failure, returns an error message string (e.g., subject dir not found, unsupported modality, no JSON, or JSON load failure).
        """
    },


    {
        "name": "mriqc_visual_inspection_based_qc",
        "module": "tool_lib.quality_control_lib",
        "description": "Perform visual inspection quality control on a specified subject and visual element based on MRIQC visual reports.",
        "detailed_schema": """
            **Parameters:**
            - subject_label (str): Subject ID with or without the 'sub-' prefix (e.g., '0027003' or 'sub-0027003').
            - visual_element_type (str): One of the following values:
                - 't1w_mosaic_brain' -> A mosaic of the brain. This mosaic is the most suitable to screen head-motion intensity inhomogeneities, global/local noise, signal leakage (for example, from the eyeballs and across the phase-encoding axis), etc.
                - 'bold_mean_bold' -> Mosaic view of the average BOLD signal.
                - 'bold_temp_std' -> Mosaic view of the temporal standard deviation.
            - output_dir (str): Absolute path to the MRIQC output root directory.

            **Outputs:**
            - Evaluation of the visual element proposed by the specialized visual qc agent.    
        """
    }
]
