descriptions = [
    {
        "name": 'afni_t1w_skull_strip',
        "module": 'tool_lib.afni',
        "description": """
            Perform skull stripping on an sMRI image using AFNI's 3dSkullStrip.
        """,
        "detailed_schema": """
            **Parameters:**
            - input_file: Path to the input anatomical t1w image.
            - output_prefix: Prefix for the output files, including the directory path.

            **Outputs:**
            - {output_prefix}_skull_stripped.nii.gz: Brain-extracted t1w file.
            - {output_prefix}_skull_stripped_mask.nii.gz: Brain mask of the brain-extracted t1w file.
        """,
    },
    {
        "name": 'afni_tissue_segmentation',
        "module": 'tool_lib.afni',
        "description": """
            Perform tissue segmentation on a skull-stripped sMRI image using AFNI's 3dSeg.

            Prerequisites: This tool must be used after t1w skull stripping, but the skull stripping step can be performed by any tool or software (like ANTs, FSL, etc.). It does not have to be AFNI 3dSkullStrip.
        """,
        "detailed_schema": """
            **Parameters:**
            - input_file: Path to the input skull-stripped image (NIfTI format).
            - output_dir: Output directory path.

            **Outputs:**
            - {output_dir}/brain_seg.nii.gz: hard brain tissue segmentation map in which each voxel is assigned a discrete label corresponding to CSF, gray matter, or white matter, used for QC.
            - {output_dir}/gray_matter_prob.nii.gz: Gray matter probability map in native space.
        """,
    },
    {
        "name": 'afni_normalize_t1w_to_mni',
        "module": 'tool_lib.afni',
        "description": """
            Normalize sMRI image to a standard mni template space using AFNI's @SSwarper.
        """,
        "detailed_schema": """
            **Parameters:**
            - input_file: Path to the raw t1w image (nii.gz format with skull).
            - output_dir: Directory where the output should be saved.
            - subid: subject id for the output files.

            **Outputs:**
            - {output_dir}/anatQQ.{subid}.nii: Normalized t1w image in mni template space.
        """,
    },
    {
        "name": 'afni_warp_gm_tissue_seg_to_mni',
        "module": 'tool_lib.afni',
        "description": """
            Warp the Gray Matter Probability Map of the tissue segmentation to MNI space using AFNI's 3dNwarpApply.

            Prerequisites: This tool must be used after 'afni_normalize_t1w_to_mni' tools.
        """,
        "detailed_schema": """
            **Parameters:**
            - path_to_gm_tissue_prob_map: Path to the gray matter probability map file in native space.
            - t1w_in_mni_file: Path to the t1w image in MNI space generated by 'afni_normalize_t1w_to_mni' tool.
            - subid: subject id for the output files.

            **Outputs:**
            - {path_to_gm_tissue_prob_map.replace('.nii.gz', '_gm_mni.nii.gz')}: The Gray Matter Probability Map in MNI space, under the same directory as the original gray matter probability map file.
        """
    },
    {
        "name": 'afni_fmri_slice_timing_correction',
        "module": 'tool_lib.afni',
        "description": """
            Perform slice-timing correction on fMRI data using AFNI's 3dTshift.
        """,
        "detailed_schema": """
            **Parameters:**
            - input_file: Path to the input fMRI file (.nii or nii.gz).
            - output_file: Path to save the slice-timing corrected file (.nii or nii.gz).
            - tpattern: Slice acquisition pattern (e.g., alt+z, seq+z). Default is alt+z.

            **Outputs:**
            - Time-shifted fMRI data saved at output_file.
        """,
    },
    {
        "name": 'afni_fmri_motion_correction',
        "module": 'tool_lib.afni',
        "description": """
            Perform motion correction using AFNI's 3dvolreg.
        """,
        "detailed_schema": """
            **Parameters:**
            - input_file: Path to the input fMRI file (.nii or nii.gz).
            - output_prefix: Prefix for the output files, including the directory path.
            - base_index: Volume index to use as registration base (default: 0).

            **Outputs:**
            - {output_prefix}_motion_corrected.nii.gz: Motion-corrected fMRI data.
            - {output_prefix}_motion.1D: Motion parameters.
            - {output_prefix}_mc_fmri_brain_mask.nii.gz: Brain mask generated from the motion-corrected fMRI data, this is only used for Motion Correction Quality Control.

        """,
    },
    # {
    #     "name": 'afni_fmri_extract_brain_mask',
    #     "module": 'tool_lib.afni',
    #     "description": """
    #         Extract brain mask from fMRI data using AFNI's 3dAutomask.
    #     """,
    #     "detailed_schema": """
    #         **Parameters:**
    #         - input_file: Path to the fMRI data.
    #         - output_prefix: Prefix for the output files, including the directory path.

    #         **Outputs:**
    #         - {output_prefix}_brain_mask.nii.gz: Brain mask generated from the fMRI data.
    #     """,
    # },
    {
        "name": 'afni_coregister_fmri_to_anat',
        "module": 'tool_lib.afni',
        "description": """
            Co-register fMRI to anatomical image using AFNI's (EPI to anat space).
        """,
        "detailed_schema": """
            **Parameters:**
            - input_fmri_file: Path to the fMRI image with skull (.nii or nii.gz) to be co-registered to the anatomical image.
            - anat_file: Path to the original anatomical (T1w) image (.nii or nii.gz) .
            - output_dir: Directory where you want all outputs to be placed.

            **Outputs:**
            - {output_dir}/brain_seg.nii.gz: t1w brain segmentation result (CSF, GM, WM), used for quality control.
            - {output_dir}/t1w_brain_skull_stripped_mask.nii.gz: t1w brain mask, used for quality control.
            - {output_dir}/{input_fmri_file_name}_fmri_in_anat_mean.nii.gz: Mean fMRI image in anat space. input_fmri_file_name is the string after removing the .nii.gz suffix from input_fmri_file.
            - {output_dir}/{input_fmri_file_name}_fmri_in_anat_mean_brain_mask.nii.gz: Brain mask of the mean fMRI image in anat space, used for quality control.
        """,
    },
    {
        "name": 'afni_normalize_fmri_to_mni',
        "module": 'tool_lib.afni',
        "description": """
            Normalize fMRI to MNI space using AFNI's afni_proc.py. 

            Prerequisites: **This tool must be used after the `afni_normalize_t1w_to_mni` tool**, which was used to normalize the T1w image to MNI space with AFNI.
            Prerequisites: **This tool must be used after the `afni_normalize_t1w_to_mni` tool**, which was used to normalize the T1w image to MNI space with AFNI.
        """,
        "detailed_schema": """
            **Parameters:**
            - fmri_file: Path to the fMRI image with skull.
            - t1w_file: Path to the T1w image with skull.
            - afni_normalized_fmri_output_dir: Directory where the normalized fMRI image obtained from AFNI will be saved. This directory must not be already exist, otherwise will cause an error. This function will automatically create this directory.
            - afni_normalized_t1w_output_dir: Directory where the normalized T1w image was saved.
            - subid: Subject ID. Must be the same as the subid used in the `afni_normalize_t1w_to_mni` function.

            **Outputs:**
            - {afni_normalized_fmri_output_dir}/{subid}_normalized_fmri_in_mni.nii.gz: Normalized fMRI image in MNI space.
            - {afni_normalized_fmri_output_dir}/{subid}_normalized_fmri_in_mni_mean.nii.gz: Mean normalized fMRI image in MNI space.
            - {afni_normalized_fmri_output_dir}/{subid}_normalized_fmri_in_mni_brain_mask.nii.gz: Brain mask of the normalized fMRI image in MNI space, used for quality control.
            - {afni_normalized_fmri_output_dir}/{subid}_fmri_mean_in_t1wspace.nii.gz: Mean fMRI image in t1w space, used for quality control.
            - {afni_normalized_fmri_output_dir}/{subid}_fmri_brain_mask_in_t1wspace.nii.gz: Brain mask of the fMRI image in t1w space, used for quality control.
            - {afni_normalized_fmri_output_dir}/t1w_brain_skull_stripped_mask.nii.gz: t1w brain mask in the original t1w space, used for quality control.
            - {afni_normalized_fmri_output_dir}/brain_seg.nii.gz: t1w brain segmentation result (CSF, GM, WM) in the original t1w space, used for quality control.
        """,
    },
    {
        "name": 'afni_spatial_smoothing',
        "module": 'tool_lib.afni',
        "description": """
            Apply spatial smoothing using AFNI's 3dmerge.
        """,
        "detailed_schema": """
            **Parameters:**
            - input_file: Path to input fmri.
            - output_file: Path to save smoothed fMRI file (.nii or nii.gz).
            - fwhm: Full-width half maximum for Gaussian kernel (default: 2.0 mm).

            **Outputs:**
            - Spatially smoothed fMRI file saved at output_file (.nii or nii.gz).
        """,
    },
    {
        "name": 'afni_temporal_filter_fmri',
        "module": 'tool_lib.afni',
        "description": """
            Conduct temporal filter on fmri data. Preprocess fMRI signal by regressing out motion, trends, and applying bandpass filtering using AFNI's 3dTproject.

            Prerequisites: This tool must be used after the `afni_fmri_motion_correction` tool.
        """,
        "detailed_schema": """
            **Parameters:**
            - input_file: Path to fMRI data.
            - output_file: Path to save the temporally filtered fMRI file (.nii or nii.gz).
            - motion_file: 1D file containing motion regressors (e.g., from afni_fmri_motion_correction).
            - low_freq, high_freq: Bandpass range in Hz.
            - polort: Polynomial detrending order.

            **Outputs:**
            - Denoised, bandpass-filtered fMRI data specified by output_file (.nii or nii.gz).
        """,
    },
]
