descriptions = [
    {
        "name": 'ants_bias_field_correction',
        "module": 'tool_lib.ants',
        "description": """
            Perform N4 Bias Field Correction using ANTs N4BiasFieldCorrection.
        """,
        "detailed_schema": """
            **Parameters:**
            - input_file: Path to input t1w file.
            - output_file: Path to save bias-corrected t1w image.
            - shrink_factor: Speed-up factor.

            **Outputs:**
            - Bias-corrected NIfTI image.
        """,
    },
    {
        "name": 'ants_skull_strip',
        "module": 'tool_lib.ants',
        "description": """
            Perform skull stripping using ANTs' antsBrainExtraction.sh script.
        """,
        "detailed_schema": """
            **Parameters:**
            - input_file: Path to T1-weighted image (NIfTI) with skull.
            - output_prefix: Prefix for the output files, including the directory path.

            **Outputs:**
            - Skull-stripped brain image and brain mask.
            - {output_prefix}BrainExtractionBrain.nii.gz: Skull-stripped brain image.
            - {output_prefix}BrainExtractionMask.nii.gz: Skull-stripped brain mask.
        """,
    },
    {
        "name": 'ants_tissue_segmentation',
        "module": 'tool_lib.ants',
        "description": """
            Perform tissue segmentation using ANTs Atropos.

            Prerequisites: This tool must be used after t1w skull stripping, but the skull stripping step can be performed by any tool or software (like AFNI, FSL, etc.). It does not have to be ANTs Atropos.
        """,
        "detailed_schema": """
            **Parameters:**
            - input_file: Path to the Skull-stripped t1w image (NIfTI format).
            - output_prefix: Prefix for segmentation outputs, including the directory path.
            - mask_file: Path to the Brain mask generated from skull stripping step.

            **Outputs:**
            - Segmentation image and probability maps. located at {output_prefix}Seg.nii.gz and {output_prefix}SegProb%02d.nii.gz.
            - {output_prefix}Seg.nii.gz: hard brain tissue segmentation map in which each voxel is assigned a discrete label corresponding to CSF, gray matter, or white matter, used for QC.
            - {output_prefix}SegProb02.nii.gz: Probability map for gray matter in native space.
        """,
    },
    {
        "name": 'ants_normalize_to_mni_template',
        "module": 'tool_lib.ants',
        "description": """
            Normalize t1w image to mni template space using ANTs antsRegistrationSyN.

            Prerequisites: This tool must be used after t1w skull stripping, but the skull stripping step can be performed by any tool or software (like AFNI, FSL, ANTs, etc.).
        """,
        "detailed_schema": """
            **Parameters:**
            - input_file: Path to the skull-stripped T1w image NIfTI file.
            - output_prefix: Prefix for output files.

            **Outputs:**
            - Normalized image and transforms. Normalized image is located at {output_prefix}Warped.nii.gz.
        """,
    },
    {
        "name": 'ants_warp_gm_tissue_seg_to_mni',
        "module": 'tool_lib.ants',
        "description": """
            Warp the Gray Matter Probability Map of the tissue segmentation to MNI space using ANTs.

            Prerequisites: This tool must be used after 'ants_normalize_to_mni_template' tool.
        """,
        "detailed_schema": """
        **Parameters:**
        - path_to_gm_tissue_prob_map: Path to the gray matter probability map file in native space.
        - ants_norm_output_prefix: Output prefix for the normalized image generated by 'ants_normalize_to_mni_template' tool.

        **Outputs:**
        - {path_to_gm_tissue_prob_map.replace('.nii.gz', '_gm_mni.nii.gz')}: The Gray Matter Probability Map in MNI space, under the same directory as the original gray matter probability map file.
        """
    }
]
