descriptions = [
    {
        "name": 'fsl_bet_t1w',
        "module": 'tool_lib.fsl',
        "description": """
            Perform brain extraction (skull stripping) on an sMRI image using FSL BET.
        """,
        "detailed_schema": """
            **Parameters:**
            - input_file: Path to the T1w image with skull.
            - output_prefix: Full path prefix (including directory) for the files (skull-stripped t1w and brain mask).
            - frac: Fractional intensity threshold (default: 0.3). Higher values means more aggressive skull stripping (tend to remove more parts).

            **Outputs:**
            - {output_prefix}_brain.nii.gz: Skull-stripped T1w image.
            - {output_prefix}_brain_mask.nii.gz: Brain mask of the skull-stripped T1w image.
        """,
    },
    {
        "name": 'fsl_fast',
        "module": 'tool_lib.fsl',
        "description": """
            Perform tissue segmentation on a skull-stripped structural image using FSL FAST.

            Prerequisites: This tool must be used after t1w skull stripping, but the skull stripping step can be performed by any tool or software (like AFNI, ANTs, etc.). It does not have to be FSL BET.
        """,
        "detailed_schema": """
            **Parameters:**
            - skull_stripped_t1w_file: Path to a skull-stripped T1-weighted NIfTI image.
            - output_prefix: Full path prefix (including directory) for all output files.

            **Outputs:**
            - CSF, GM, and WM partial volume maps and segmentation labels with the specified prefix. 
            - {output_prefix}_pve_0/1/2.nii.gz, specifically {output_prefix}_pve_1.nii.gz is the gray matter probability map in native space.
            - {output_prefix}_seg.nii.gz: hard brain tissue segmentation map in which each voxel is assigned a discrete label corresponding to CSF, gray matter, or white matter, used for QC.
        """,
    },
    {
        "name": 'fsl_normalize_t1w_to_mni',
        "module": 'tool_lib.fsl',
        "description": """
            Normalize T1w image to MNI space using FSL.

            Prerequisites: This tool must be used after t1w skull stripping, but the skull stripping step can be performed by any tool or software (like AFNI, ANTs, etc.).
        """,
        "detailed_schema": """
            **Parameters:**
            - skull_stripped_t1w_file: Path to skull-stripped (brain-only) T1-weighted image.
            - full_head_t1w_file: Path to full-head (with skull) T1-weighted image.
            - output_prefix: Full path prefix (including directory) for all output files.

            **Outputs:**
            - {prefix}_anat2mni_affine.mat: Affine matrix from (brain) T1w to MNI brain (FLIRT).
            - {prefix}_anat2mni_warpcoef.nii.gz: Nonlinear warp coefficients (FNIRT --cout).
            - {prefix}_anat_mni_brain.nii.gz: Skull-stripped T1w warped into MNI brain space.
        """,
    },
    {
        "name": 'fsl_warp_gm_tissue_seg_to_mni',
        "module": 'tool_lib.fsl',
        "description": """
            Warp the Gray Matter Probability Map of the tissue segmentation to MNI space using FSL.

            Prerequisites: This tool must be used after 'fsl_normalize_t1w_to_mni' tool.
        """,
        "detailed_schema": """
            **Parameters:**
            - path_to_gm_tissue_prob_map: Path to the gray matter probability map file in native space.
            - warpcoef: Nonlinear warp coefficients file generated by 'fsl_normalize_t1w_to_mni' tool.

            **Outputs:**
            - {path_to_gm_tissue_prob_map.replace('.nii.gz', '_gm_mni.nii.gz')}: The Gray Matter Probability Map in MNI space, under the same directory as the original gray matter probability map file.
        """
    },
    {
        "name": 'fsl_skullstrip_fmri',
        "module": 'tool_lib.fsl',
        "description": """
            Perform brain extraction on a 4D fMRI image using FSL BET.
        """,
        "detailed_schema": """
            **Parameters:**
            - input_file: Path to the 4D fMRI NIfTI image.
            - output_prefix: Full path prefix (including directory) for the files (skull-stripped fmri and brain mask).
            - frac: Fractional intensity threshold for BET (default: 0.3).

            **Outputs:**
            - {output_prefix}_skull_stripped_fmri.nii.gz: Skull-stripped fMRI image.
            - {output_prefix}_brain_mask.nii.gz: Brain mask of the skull-stripped fMRI image in the original fmri space.
        """,
    },
    {
        "name": 'fsl_slicetimer',
        "module": 'tool_lib.fsl',
        "description": """
            Slice-timing correction for fMRI using FSL Slicetimer.
        """,
        "detailed_schema": """
            **Parameters:**
                input_file: Path to the 4D fMRI input file.
                output_file: Path to save the slice-time corrected file.
                TR: TR (time of repetition) in seconds. Default is 2.0.

            **Outputs:**
            - A 4D slice-time-corrected fMRI image.
        """,
    },
    {
        "name": 'fsl_motion_correct',
        "module": 'tool_lib.fsl',
        "description": """
            Perform motion correction on a 4D fMRI image using FSL MCFLIRT.
        """,
        "detailed_schema": """
            **Parameters:**
            - input_file: Path to the input fMRI NIfTI image.
            - output_file: Path to save the motion-corrected image.

            **Outputs:**
            - output_file: Path to the motion-corrected fMRI image.
            - {output_file}.par: Motion parameters.
            - A brain mask of the motion-corrected fMRI in the same directory as the output_file. named as 'mc_fmri_brain_mask.nii.gz'. This is only used for Motion Correction Quality Control.
        """,
    },
    {
        "name": 'fsl_coregister_func_to_anat',
        "module": 'tool_lib.fsl',
        "description": """
            Co-register fMRI (EPI) to T1w structural image using FSL.
        """,
        "detailed_schema": """
            **Parameters:**
            - fmri_file: Path to the 4D fMRI image with skull.
            - t1w_file: Path to the T1-weighted structural image with skull (whole head).
            - output_prefix: Full path prefix (including directory) for output files, e.g. "{output_prefix}_func2anat.mat"

            **Outputs:**
            - {output_prefix}_func2anat.mat: Affine matrix from mean fMRI (EPI) to T1w image.
            - {output_prefix}_mean_func2anat.nii.gz: Mean fMRI in T1w space.
            - {output_prefix}_mean_func2anat_brain_mask.nii.gz: Brain mask of the mean fMRI in T1w space, used for quality control.
            - {output_prefix}_t1w_proc.anat/T1_biascorr_brain_mask.nii.gz: Brain mask of the T1w image used for quality control.
            - {output_prefix}_t1w_proc.anat/T1_fast_seg.nii.gz: Segmentation of the T1w image used for quality control.
        """,
    },
    {
        "name": 'fsl_normalize_func_to_mni',
        "module": 'tool_lib.fsl',
        "description": """
            Normalize fMRI to MNI space using FSL.

            Prerequisites: This function **must** be used after the `fsl_coregister_func_to_anat` function, which was used to co-register the fMRI to the T1w image.
        """,
        "detailed_schema": """
            **Parameters:**
            - fmri_file: Path to the fMRI image with skull.
            - t1w_file: Path to the T1w image with skull.
            - func2struct_mat: Path to the fMRI-to-T1w affine matrix obtained from `fsl_coregister_func_to_anat` function.
            - output_prefix: Full path prefix (including directory) for the files.

            **Outputs:**
            - {output_prefix}_func_mni.nii.gz: fMRI in MNI space.
            - {output_prefix}_mean_func_mni.nii.gz: Mean fMRI in MNI space.
            - {output_prefix}_mean_func_mni_brain_mask.nii.gz: Brain mask of the mean fMRI in MNI space, used for quality control.
        """,
    },
    {
        "name": 'fsl_spatial_smooth',
        "module": 'tool_lib.fsl',
        "description": """
            Apply spatial smoothing to an image using FSL fslmaths.
        """,
        "detailed_schema": """
            **Parameters:**
            - input_file: Path to the input fMRI image.
            - output_file: Path to save the smoothed image.
            - fwhm: Full-width at half maximum in millimeters (default: 2.0mm).

            **Outputs:**
            - Smoothed image using the given FWHM.
        """,
    },
    {
        "name": 'fsl_temporal_filter',
        "module": 'tool_lib.fsl',
        "description": """
            Apply temporal band-pass filtering to a 4D fMRI image using FSL fslmaths -bptf.
        """,
        "detailed_schema": """
            **Parameters:**
            - input_file: Path to the input fMRI image.
            - output_file: Path to save the temporally filtered fmri image.
            - TR: Repetition time (TR) in seconds.
            - highpass_freq: High-pass frequency threshold, frequeny higher than this value will pass.
            - lowpass_freq: Low-pass frequency threshold, frequeny lower than this value will pass.

            **Outputs:**
            - Band-pass filtered fMRI time series.
        """,
    },
]
