descriptions = [
    {
        "name": "construct_functional_brain_connectivity",
        "type": "function",
        "module": "tool_lib.brain_connectome_analysis",
        "description": "Construct the functional brain connectivity from a single-subject fMRI image file and the parcellation atlas.",
        "detailed_schema": """
            **Parameters:**
            - fmri_img_path: (str), the path of the fMRI NIfTI image file (.nii or .nii.gz) for a single subject, with shape (W, H, D, T), where W,H,D are the spatial dimensions, and T is the time dimension.
            - parcellation_atlas: (str), choose from ['AAL90', 'Schaefer200', 'HCP360'], the parcellation atlas.
            - method: (str), choose from ['correlation', 'causality'], default is 'correlation'.

            **Outputs:**
            - (numpy array) The functional brain connectivity. with shape (num_ROIs, num_ROIs).
        """
    },
    {
        "name": "BrainNetworkTransformer",
        "type": "pytorch model class",
        "module": "tool_lib.brain_connectome_analysis",
        "description": "One of the state-of-the-art models for functional brain connectome analysis. A graph transformer-based model for brain network analysis.",
        "detailed_schema": """
            **Parameters:**
            - num_rois: (int). number of ROIs.
            - num_layers: (int). number of layers of the model.
            - num_clusters: (int). number of ROIs clusters. Should set as a small number when training on a small dataset.
            - hidden_size: (int). hidden size of FFN in transformer encoder.
            - num_heads: (int). number of heads of transformer encoder. Usually set as 2. Note that the number of heads **must be divisible by the input feature size (number of ROIs).**
            - pred_task: (str). 'classification' or 'regression'.
            - num_classes: (int). number of classes for classification task.

            ---
            `forward` Parameters:
            - node_feature: (torch.tensor), with shape (batch_size, num_rois, node_feature_size), node feature matrix is the original brain connectivity matrix (without sparsification).

            `forward` Returns:
            - (torch.tensor) The output logits w/o softmax. Shape: (batch_size, output_dim), e.g., for binary classification, output_dim=2.
        """
    },
    {
        "name": "sparsify_connectivity_matrices",
        "type": "function",
        "module": "tool_lib.brain_connectome_analysis",
        "description": "A function to sparsify the functional brain connectivity matrices for neurograph model.",
        "detailed_schema": """
            Parameters:
            - orig_connectivity_matrices (torch.Tensor): All subjects' original brain connectivity matrices with shape (num_subjects, num_ROIs, num_ROIs).
            - keep_ratio: (float), The keep_ratio (range from 0 to 1) of edges to keep based on their absolute weight.
            - only_positive: (boolean), whether keep only positive correlation. Default is True.

            Returns:
            - (torch.Tensor) The sparsified connectivity matrices with the same shape as orig_connectivity_matrices.
        """
    },
    {
        "name": "NeuroGraph",
        "type": "pytorch model class",
        "module": "tool_lib.brain_connectome_analysis",
        "description": "A graph neural network-based model for functional brain connectome analysis with residual connection.",
        "detailed_schema": """
            **Parameters:**
            - hidden_channels: (int). Number of hidden channels used by each graph convolution layer.
            - num_rois: (int). Number of brain regions of interest (ROIs).
            - num_layers: (int). Number of graph convolution layers in the model.
            - hidden: (int). Hidden dimension used by the downstream MLP classifier/regressor.
            - task: (str). Task type, usually `'classification'` or `'regression'`.

            ---
            `forward` Parameters:
            - m: (torch.tensor), with shape (batch_size, num_rois, num_rois). The adjacency matrix of the brain graph generated by `sparsify_connectivity_matrices`.
            - node_feature: (torch.tensor), with shape (batch_size, num_rois, node_feature_size)

            `forward` Returns:
            - (torch.tensor) The output logits. Shape: (batch_size, output_dim), e.g., for binary classification, output_dim=2.
        """
    }

]